# Generated by Django 3.0.3 on 2020-03-03 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "tag",
                    models.CharField(
                        help_text="String uniquely identifying the version",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="version tag",
                    ),
                ),
                (
                    "rel_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Release date of the tag",
                        verbose_name="release date",
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True, help_text="Free-form text", max_length=4096
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="entity",
            options={"verbose_name_plural": "entities"},
        ),
        migrations.AlterModelOptions(
            name="quantity",
            options={"verbose_name_plural": "quantities"},
        ),
        migrations.AddField(
            model_name="datafile",
            name="release_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_files",
                to="browse.Release",
            ),
        ),
    ]
