# Generated by Django 3.2.16 on 2022-11-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='json_file',
            field=models.FileField(blank=True, editable=False, help_text='A compressed JSON dump of the release, ready to be downloaded', upload_to=''),
        ),
    ]
