# Generated by Django 3.0.3 on 2020-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20200303_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='metadata',
            field=models.TextField(blank=True, help_text='JSON record containing metadata for the file', max_length=32768, verbose_name='JSON-formatted metadata'),
        ),
    ]
