# Generated by Django 3.0.3 on 2020-06-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0003_auto_20200611_1828"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datafile",
            name="release_tag",
        ),
        migrations.AddField(
            model_name="datafile",
            name="release_tag",
            field=models.ManyToManyField(
                blank=True, related_name="data_files", to="browse.Release"
            ),
        ),
    ]
