# Generated by Django 3.0.3 on 2020-06-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_auto_20200630_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='release_tag',
            new_name='release_tags',
        ),
    ]
