# Generated by Django 3.0.3 on 2020-07-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_auto_20200630_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='comments',
            new_name='comment',
        ),
    ]
