# Generated by Django 4.2.4 on 2023-08-10 14:04

import browse.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("browse", "0005_alter_release_release_document_mime_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="name",
            field=models.CharField(
                help_text="Descriptive name for this entity",
                max_length=256,
                validators=[browse.models.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="name",
            field=models.CharField(
                help_text="Descriptive name for this quantity",
                max_length=256,
                validators=[browse.models.validate_name],
            ),
        ),
    ]
