# Generated by Django 4.2.4 on 2023-08-11 13:46

import browse.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("browse", "0006_alter_entity_name_alter_quantity_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafile",
            name="metadata",
            field=models.TextField(
                blank=True,
                help_text="JSON record containing metadata for the file",
                max_length=32768,
                null=True,
                validators=[browse.models.validate_json],
                verbose_name="JSON-formatted metadata",
            ),
        ),
    ]
